begin;
set local role postgres;
set local search_path = public, testing, extensions;
select plan(18);
select has_column('public','conversation_user_states','archived_at','archive is per-user');
select has_table('private','moderation_appeals','appeals are stored privately');
select has_function('public','get_privacy_settings',array[]::text[],'privacy settings RPC exists');
select has_function('public','list_hidden_profiles',array['integer'],'hidden profiles RPC exists');
select has_function('public','list_blocked_profiles',array['integer'],'blocked profiles RPC exists');
select has_function('public','unblock_user',array['uuid'],'unblock RPC exists');
select has_function('public','set_conversation_archived',array['uuid','boolean'],'archive RPC exists');
select has_function('public','list_archived_conversation_ids',array[]::text[],'archived list RPC exists');
select has_function('public','get_my_active_sanction',array[]::text[],'sanction RPC exists');
select has_function('public','submit_moderation_appeal',array['uuid','text'],'appeal RPC exists');
select function_privs_are('public','unblock_user',array['uuid'],'anon',array[]::text[],'anon cannot unblock');
select function_privs_are('public','unblock_user',array['uuid'],'authenticated',array['EXECUTE'],'user can unblock');
select function_privs_are('public','set_conversation_archived',array['uuid','boolean'],'authenticated',array['EXECUTE'],'user can archive');
select function_privs_are('public','submit_moderation_appeal',array['uuid','text'],'authenticated',array['EXECUTE'],'user can appeal');
select table_privs_are('private','moderation_appeals','authenticated',array[]::text[],'appeal rows are not directly exposed');
select trigger_is('public','messages','messages_rate_limit','private','guard_message_rate_limit','messages are rate limited');
select col_is_fk('private','moderation_appeals','sanction_id','appeal references sanction');
select col_is_unique('private','moderation_appeals',array['user_id','sanction_id'],'one appeal per sanction');
select * from finish();
rollback;
